version: "2"

run:
  timeout: 5m

linters:
  enable:
    # Enabled by default
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Additional useful linters
    - gocyclo
    - revive
    - misspell
    - goconst
    - bodyclose
    - errorlint
    - nolintlint

formatters:
  enable:
    - goimports







